{% set name = "Flask-JWT-Extended" %}
{% set version = "4.3.1" %}
{% set sha256 = "ad6977b07c54e51c13b5981afc246868b9901a46715d9b9827898bfd916aae88" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  skip: True  # [py<36]
  script: "{{ PYTHON }} -m pip install . -vv"


requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python >=3.6
    - flask >=1.0,<3.0
    - pyjwt >=2.0,<3.0
    - cryptography >=3.0,<4.0
    - werkzeug >=0.14

test:
  imports:
    - flask_jwt_extended
  requires:
    - pip
    - python <3.10
  commands:
    - pip check

about:
  home: https://github.com/vimalloc/flask-jwt-extended
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Flask JWT extension'

  description: |
    A Flask JWT extension that supports refresh tokens, blacklisting/revoking tokens,
    and token freshness (for accessing critical views)
  dev_url: https://github.com/vimalloc/flask-jwt-extended
  doc_url: https://github.com/vimalloc/flask-jwt-extended#readme

extra:
  recipe-maintainers:
    - lvoliveira
    - nicoddemus
    - igortg
    - synapticarbors
