travis:
  secure:
    BINSTAR_TOKEN: MsK4APmHkrkE/fZ5IHDtj0Kh2wVPrnpYMHHYCOns80geXEBS0i7BthBLJkMcgGfAKBHQa91MVTbzr8qtvGP3z/h6WIhvnnT10Bp4E80MF+ZA41iUWSe8f/8S9kxa+LxJbtxrYkJHxH5dmdal1ggp0cUqao4PfwcRasQBg+zZgj8z5KQ1L31tLs0ndCsjG0lGb9WJXqfhnErcHCcfY/HsjR2OWKOs4CmMgLooDqHkHIIsEzrov57usTFFmTfy6TqTT05N4kz5ylDTCap12NNBh3wAAXCKscjHU0l9GI0XAYNSQ8molQvOFVU1985nCfp83wm066Pct4VF+JRod7vTy4aJzgg+v+RoVrl+qyrnZoToOZocS3ym4FUqf5KTz2Eso+gEoRCJFLQ46aJDAn5tAPLUpz6gUlHMZJWXn2XPubogVmVrVvETZx0VJ7tqxUCYg4sgAbIhBfmjuO5gUJRkDkNsubIOB8ELSq1cQ2+pgQUoonKcNzFV2rcMC7WaIHGDl/M8VcMOmyB3i+pP9EADJb1J9e38vhfEtLTBFYiP+Nb7kpeceR3KDfJwHo41T0g3Jpr9oqvj/4+oKcoC61TmoeywAFhdlu0Xt/wuHEzVQ13N8a24mdi5zehAf92l8Uz+wt1OHrcYiUSuUremzOxtQw+J0E8z8Sjoz40jKEM1NUM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
