travis:
  secure:
    BINSTAR_TOKEN: fA+OrUBRag7BSFoXBu6f4YSN/+o5PvsaFaVPs2tm4ePHzUMl0vV0A1NjUgEAfKKIy+Xgq+NuwzWYcEYe42LETy5seFYcyK5l//EfMiBPeW9pf5lQyTwN+NDyCTbmbF8FNBVad75Zq0VlGlpsydl8p5wWGvrmztte9pa8NulOq5ADpM+EqOPLlMMpZbOMaC/bQ4QcrJgYQ1LdTBfirnaouH9buHwv63ImkDmJLjBpYA30babQ9U24GoiPcGcYhsrXeEg+M6+mfaxgvbn2/4AVS1c+Ojgq02vNGIfAY2i4K2SZwsLJzy7mXsyE8m7tNirZ3oS9wNJYL/77n4kciz7ueOG9pxNyv4FVTG7sDaPQM3E86jZsvVMYGTBoggQTW2AD+zhf9lXqVbkerICh4oYvjoMFQuYTkSpiMfxACieEfhIF9Glr5C/ASQJrUNWMHfK107fBP1elTurKO0tBQNEYhRzUeMYXkqNWgEHdkWwwYcypEtqbAQrhzS+6cRP+1x9cWDoMLhCFO1vO0tauvRDqwgWVswbtiTeEpa1CjcKMNjgBd3UOhlAJ5FO1i/coxVcrOk+qKHbdF6MKLkgTN05PTrEB9pM+BUXAeaRgu2TflBkzg9NnI+QdgNI3w51p+yafub5FtrFOznB5OjkPeTiccXtQya3j7rKkAdz+jKR2HR4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
